name: upload to production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /portfolio/Hendrik_Van_Beersel/CV/portfolio
            git pull origin main
            npm ci
            npm run build
            docker build -t portfolio-hendrik .
            docker run --rm -d \
            --name portfolio-hendrik \
            -p 443:433 \
            -v /opt/certificates:/portfolio/Hendrik_Van_Beersel/CV/cert \
            -v /opt/nginx.conf:/portfolio/Hendrik_Van_Beersel/CV/nginx.conf \
            portfolio-hendrik
