name: upload to production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /portfolio/Hendrik_Van_Beersel/CV/portfolio
            git pull origin main
            npm ci
            npm run build
            docker stop portfolio-hendrik
            docker rm portfolio-hendrik
            docker build -t portfolio-hendrik .
            docker run --name portfolio-hendrik --rm -d -p 443:8080 portfolio-hendrik
